In [40]:
'''
卷积操作
Parameters:
1.input
2.weight(卷积核)
3.bias
4.stride(步径)(可以是单个数，也可以是元组)
.......

1.卷积核与输入图像（从第一位开始）相乘再相加
2.stride决定每次横向以及纵向移动几位,比如stride = 2时,横向每次移动两位，移至尽头时，再纵向移动两位，开始横向扫描
'''

'\n卷积操作\nParameters:\n1.input\n2.weight(卷积核)\n3.bias\n4.stride(步径)(可以是单个数，也可以是元组)\n.......\n\n1.卷积核与输入图像（从第一位开始）相乘再相加\n2.stride决定每次横向以及纵向移动几位,比如stride = 2时,横向每次移动两位，移至尽头时，再纵向移动两位，开始横向扫描\n'

In [41]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter

In [42]:
#输入
input = torch.tensor([[1,2,0,3,1],
                      [0,1,2,3,1],
                      [1,2,1,0,0],
                      [5,2,3,1,1],
                      [2,1,0,1,1]])
#input的shape有要求：(minbatch,in_channels:输入图像的通道数,H_i,W_i)

#卷积核
kernel = torch.tensor([[1,2,1],
                       [0,1,0],
                       [2,1,0]])
#kernel的shape有要求：(out_channels：通过卷积之后输出的通道数,in_channels,H_k,H_w)

#验证卷积操作结果
print(input.shape)
print(kernel.shape)
#显然不满足条件
input = torch.reshape(input,(1,1,5,5))
kernel = torch.reshape(kernel,(1,1,3,3))

output = F.conv2d(input,kernel,stride = 1)
print(output)

output2 = F.conv2d(input,kernel,stride = 2)
print(output2)

#padding 在输入中填充

output3 = F.conv2d(input,kernel,stride = 1,padding = 1)
print(output3)





torch.Size([5, 5])
torch.Size([3, 3])
tensor([[[[10, 12, 12],
          [18, 16, 16],
          [13,  9,  3]]]])
tensor([[[[10, 12],
          [13,  3]]]])
tensor([[[[ 1,  3,  4, 10,  8],
          [ 5, 10, 12, 12,  6],
          [ 7, 18, 16, 16,  8],
          [11, 13,  9,  3,  4],
          [14, 13,  9,  7,  4]]]])


In [43]:
'''
1.in_channels:输入图片的通道数      3
2.out_channels:经过卷积输出的通道数 6 
3.kernel_size:卷积核的size         3
4.stride:步径大小
5.padding:
6.padding_mode:zeros(一般情况)
'''

'\n1.in_channels:输入图片的通道数      3\n2.out_channels:经过卷积输出的通道数 6 \n3.kernel_size:卷积核的size         3\n4.stride:步径大小\n5.padding:\n6.padding_mode:zeros(一般情况)\n'

In [44]:
'''
in_channels & out_channels
eg1:in_channels = 1   out_channels = 2 --->两个卷积核 分别对input进行卷积操作

'''

'\nin_channels & out_channels\neg1:in_channels = 1   out_channels = 2 --->两个卷积核 分别对input进行卷积操作\n\n'

In [45]:
test_dataset = torchvision.datasets.CIFAR10(root = "./dataset",train = False,transform = torchvision.transforms.ToTensor(),download = True)

dataloader = DataLoader(test_dataset,batch_size = 64)

Files already downloaded and verified


In [46]:
for data in dataloader:
    dataset,label = data
    print(dataset.shape)

torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 3

In [47]:
#定义一层卷积层的网络
class Tudui(nn.Module):
    def __init__(self):
        super(Tudui,self).__init__()
        self.conv1 = nn.Conv2d(in_channels = 3,out_channels = 6,kernel_size = 3,stride = 1,padding = 0)

    def forward(self,input):
        output = self.conv1(input)
        return output

In [48]:
tudui = Tudui()
data,_ = test_dataset[0]
print(tudui(data).shape)

torch.Size([6, 30, 30])


In [49]:
print(tudui)

Tudui(
  (conv1): Conv2d(3, 6, kernel_size=(3, 3), stride=(1, 1))
)


In [52]:
count = 0
writer = SummaryWriter("Conv_pic")
for data in dataloader:
    imgs,targets = data
    output = tudui(imgs)
    print(output.shape)
    count += 1
    output = torch.reshape(output,(-1,3,30,30))
    writer.add_images("conv_pic",output,count)
    writer.close()
print(count)

torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 30, 30])
torch.Size([64, 6, 3