In [3]:
print('hello')

hello


# 一、导入库

In [4]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

# 二、张量

In [5]:
torch.__version__

'2.0.0+cu118'

## 2.1张量函数创建方法

In [6]:
#通过列表创建张量
t = torch.tensor([1,2])
t


tensor([1, 2])

In [7]:
#通过元组创建张量
torch.tensor((1,2))

tensor([1, 2])

In [8]:
#通过数组创建张量
#numpy与tensor的转换
a = np.array((1,2))
a

array([1, 2])

In [9]:
t1 = torch.tensor(a)
t1
#dtype:通过返回结果，我们可以看出张量也有dtype类型

tensor([1, 2], dtype=torch.int32)

In [10]:
print(type(t))
print(type(t1))

<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [11]:
print(a.dtype)
print(t.dtype)
print(t1.dtype) 
#从这里的输出结果我们可以看出：整数型数组默认创建int32(整型)类型，而张量则默认创建int64(长整型)类型


int32
torch.int64
torch.int32


In [12]:
a = np.array([1.1,2.2])
print(a.dtype)
print(torch.tensor(a).dtype)#tensor继承array的数据类型
print(torch.tensor([1.1,2.2]).dtype)
#从输出结果可以看出：创建浮点型数组时，张量默认float32(单精度),而Array则是默认float64(双精度浮点型)

float64
torch.float64
torch.float32


In [13]:
#布尔型张量
t2 = torch.tensor([True,False])
t2

tensor([ True, False])

In [14]:
#复数型张量
a = torch.tensor(1+2j)
a

tensor(1.+2.j)

In [15]:
#通过dtype参数，在创建张量的过程中设置输出结果
torch.tensor([1.1,2.7],dtype=torch.int16)

C:\Users\86138\AppData\Local\Temp\ipykernel_18540\928534527.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  torch.tensor([1.1,2.7],dtype=torch.int16)


tensor([1, 2], dtype=torch.int16)

In [16]:
#通过numpy数组
a = np.array([1,2,3])
x = torch.from_numpy(a)
print(x)
x1 = torch.tensor(a)
print(x1)


tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [17]:
#通过已知张量
x_ones = torch.ones_like(x1)
print(x_ones)
x_zeros = torch.zeros_like(x1)
print(x_zeros)

tensor([1, 1, 1], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)


In [18]:
#已知形状定义张量，可以rand,ones,zeros
shape=(2,3)
rand_tensor = torch.rand(shape)
print(rand_tensor)
ones_tensor = torch.ones(shape)
print(ones_tensor)
zeros_tensor = torch.zeros(shape) 
print(zeros_tensor)

tensor([[0.8932, 0.9191, 0.2619],
        [0.9163, 0.1667, 0.6743]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [41]:
shape = [2,2]
rand_tensor_1 = torch.rand(shape)
print(rand_tensor_1)
zeros_tensor_1 = torch.zeros(2,2)
print(zeros_tensor_1)

tensor([[0.6254, 0.9716],
        [0.7490, 0.5306]])
tensor([[0., 0.],
        [0., 0.]])


In [44]:
#补充：全局初始化数据类型
torch.set_default_tensor_type(torch.DoubleTensor)
print(torch.tensor([1.0,2.0]).dtype)

torch.float64


## 2.2张量类型的转化

In [20]:
'''张量类型的隐式转化
和Numpy中的array相同,
当张量各个元素属于不同类型时候，
系统会自动进行隐式转化'''
print(torch.tensor([1.1,2]).dtype)
print(torch.tensor([True,2.2]))

torch.float32
tensor([1.0000, 2.2000])


In [21]:
'''
可以用.float(),.int(),.double(),.short()进行直接转化
后续操作中会经常将整数转化成浮点数
'''
print(t.float())
print(t.double())
print(t.short())

tensor([1., 2.])
tensor([1., 2.], dtype=torch.float64)
tensor([1, 2], dtype=torch.int16)


## 2.3张量的维度与形变（标量->向量->矩阵->）

In [22]:
# 张量是一组数的结构化表示，在张量中高维数组与Numpy中的Array类似

### 2.3.1创建高维向量

In [23]:
#用简单序列创建一维数组
t1 = torch.tensor([1,2])
#ndim查看张量维度
print(t1.ndim)
#使用shape查看形状
print(t1.shape)#包含几个元素
#使用size一样
print(t1.size())
#注：和numpy不同，Pytorch中size方法返回结果和shape属性结果一样

#还有两个常用的
#len 返回拥有几个(N-1)维元素
print(len([1,2,3]))
print(len(t1))
#numel返回一共有几个数，最底层
print(t1.numel())


1
torch.Size([2])
torch.Size([2])
3
2
2


In [24]:
#使用“序列”的“序列”创建二维数组
t2 = torch.tensor([[1,2],[3,4]])
t2
print(t2.ndim)
print(t2.shape)
print(t2.size())
print(len(t2))
print(len([[1,2],[3,4]]))#返回的是最外面的里面有几个元素
print(torch.numel(t2))
print(t2.numel())

2
torch.Size([2, 2])
torch.Size([2, 2])
2
2
4
4


In [25]:
#零维张量(标量)
#该类型张量只包含一个元素，但又不是单独的一个元素
t0 = torch.tensor([1])
print(t0)
print(f't0的维度是:{t0.ndim}')
#零维张量
t = torch.tensor(1)
print(t)
print(f't的维度是:{t.ndim}')
print(f't的形状是:{t.shape}')
print(f't的元素个数是:{t.numel()}')
#1与torch.tensor(1)的区别：后者可以放在GPU上训练

tensor([1])
t0的维度是:1
tensor(1)
t的维度是:0
t的形状是:torch.Size([])
t的元素个数是:1


In [26]:
#高维向量
#一般来说，三维以及以上的向量，最常见的还是三维向量，可以理解为二维数组或者矩阵的集合


In [27]:
a1 = np.array([[1,2,3],[4,5,6]])
print(a1)
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [28]:
t3 = torch.tensor([a1,a2])
print(t3)


tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]], dtype=torch.int32)


C:\Users\86138\AppData\Local\Temp\ipykernel_18540\2145693026.py:1: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_new.cpp:248.)
  t3 = torch.tensor([a1,a2])


In [29]:
print(t3.ndim)
print(t3.shape)
print(len(t3))
print(t3.numel())

3
torch.Size([2, 2, 3])
2
12


### 2.3.2张量的形变

In [30]:
#张量作为数字的结构化集合，其结构也是可以根据实际需求进行灵活调整

In [31]:
#flatten拉平，(就是将任意维度都变成一维，零维也变成一维)
print(t2)
t2.flatten()

tensor([[1, 2],
        [3, 4]])


tensor([1, 2, 3, 4])

In [32]:
print(t3)
t3.flatten()

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]], dtype=torch.int32)


tensor([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6], dtype=torch.int32)

In [33]:
#注：如果将零维张量使用flatten,则会将其转化为一维张量
print(t)
print(t.flatten())
print(t.flatten().ndim)

tensor(1)
tensor([1])
1


In [34]:
#reshape方法：任意变形
print(t1)
print(t1.reshape(2,1))#reshape转化后的维度有该方法输入的参数个数决定
print(t1.reshape(2,1).shape)

tensor([1, 2])
tensor([[1],
        [2]])
torch.Size([2, 1])


In [35]:
print(t1.reshape(2))
#另一种表达形式：
t1.reshape(2, )

tensor([1, 2])


tensor([1, 2])

In [36]:
print(t1.reshape(1,2))

print(t1.reshape(1,1,2))#只包含一个矩阵，并且这个矩阵是一行两列的矩阵

print(t1.reshape(1,2,1))#只包含一个矩阵，并且这个矩阵是两行一列的矩阵


tensor([[1, 2]])
tensor([[[1, 2]]])
tensor([[[1],
         [2]]])


In [37]:
print(t3)
print(t3.numel())
print(t3.reshape(12))
print(t3.device)

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]], dtype=torch.int32)
12
tensor([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6], dtype=torch.int32)
cpu


## 2.3张量的操作


In [38]:
#将张量移至GPU上训练
if torch.cuda.is_available():
    t3=t3.to('cuda')
print(t3.device)

cuda:0


In [53]:
#！！！！arange&range传入的参数不是列表，就是一个一个传入即可
print(torch.arange(3))#start默认为0，step默认为1
print(torch.arange(0,5,2))
print(torch.arange(3).dtype)
print(torch.range(0,3))#range比arange多一个数,并且数据类型为浮点型，这里的64是因为之前设置了一个全局的改变数据类型，一般是3位
print(torch.range(0,3).dtype)

tensor([0, 1, 2])
tensor([0, 2, 4])
torch.int64
tensor([0., 1., 2., 3.])
torch.float64


C:\Users\86138\AppData\Local\Temp\ipykernel_18540\3981512778.py:5: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  print(torch.range(0,3))#range比arange多一个数
C:\Users\86138\AppData\Local\Temp\ipykernel_18540\3981512778.py:6: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  print(torch.range(0,3).dtype)


In [55]:
for i in torch.arange(10):
    print(i)

tensor(0)
tensor(1)
tensor(2)
tensor(3)
tensor(4)
tensor(5)
tensor(6)
tensor(7)
tensor(8)
tensor(9)


In [60]:
#遇到sapce要注意:这里的step不是步长，而是元素的个数
print(torch.linspace(0,10,5))#这里的区别是：最后一个step参数是数组的元素个数
print(torch.logspace(0,10,10))

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
tensor([1.0000e+00, 1.2915e+01, 1.6681e+02, 2.1544e+03, 2.7826e+04, 3.5938e+05,
        4.6416e+06, 5.9948e+07, 7.7426e+08, 1.0000e+10])


In [69]:
print(torch.eye(3))
#full填充
print(torch.full([2,2],5))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[5, 5],
        [5, 5]])


In [77]:
#cat连接,传入的参数是张量列表
a = torch.rand([2,2])
b = torch.rand([2,3])
c=torch.cat([a,b],dim=1)#除了被连接的维度之外，其他维度相同
print(c)
print(c.dtype)
print(c.shape)

tensor([[0.5362, 0.5711, 0.0700, 0.6682, 0.1511],
        [0.3174, 0.5047, 0.0592, 0.3372, 0.5666]])
torch.float64
torch.Size([2, 5])


In [80]:
#chunk分割张量
c,d = torch.chunk(torch.rand([3,2]),2,dim=1)#dim默认为0
print(c)
print(d)

tensor([[0.7392],
        [0.3179],
        [0.1950]])
tensor([[0.8608],
        [0.9938],
        [0.4907]])


In [93]:
#？？？gather沿着某一维度去取一些变量,dim的值是几，就从该dim中选取元素进行重组
t = torch.rand([3,3])
print(t)
print(torch.gather(t,0,torch.tensor([[1,0,2],[1,0,2],[1,0,2]])))#out[i][j]=input[index[i][j]][j] 就是改变元素行的索引，列索引不变，那其实就是在每一列中进行变换，即每一列取哪一行的元素作为这个未知的元素

tensor([[0.7938, 0.2450, 0.3411],
        [0.9768, 0.0221, 0.2958],
        [0.1501, 0.5522, 0.2697]])
tensor([[0.9768, 0.2450, 0.2697],
        [0.9768, 0.2450, 0.2697],
        [0.9768, 0.2450, 0.2697]])


In [ ]:
#scatter_



